import { addDays, formatISO } from "date-fns";
import { TimTask } from "@/types/tim";

const today = new Date();

export const sampleTasks: TimTask[] = [
  {
    id: "urgent-1",
    title: "대표님 보고용 A&R 주간 리포트 정리",
    description: "신규 수집 곡 12곡 요약, 키워드 분류 포함",
    startDate: formatISO(today),
    category: "URGENT",
    isStarred: true,
  },
  {
    id: "urgent-2",
    title: "미국 작가 송 피드백 전달",
    description: "협업 진행 결과 및 수정 요청",
    startDate: formatISO(addDays(today, 1)),
    category: "URGENT",
    isStarred: false,
  },
  {
    id: "weekly-1",
    title: "다음 주 송캠프 후보 큐레이션",
    description: "장르/언어별 1차 리스트업",
    startDate: formatISO(addDays(today, 3)),
    category: "WEEKLY",
  },
  {
    id: "weekly-2",
    title: "라틴 시장 타겟 라이터 리서치",
    description: "상위 5명 연락처 업데이트",
    startDate: formatISO(addDays(today, 6)),
    category: "WEEKLY",
  },
  {
    id: "collab-1",
    title: "협업 · 싱글 Topline 의뢰",
    description: "A&R 협업 세팅",
    startDate: formatISO(addDays(today, 2)),
    category: "COLLAB",
    collabDetails: {
      trackProducer: "Liam Park",
      topLiner: "Hana J",
      targetArtist: "YUNA",
      deadline: formatISO(addDays(today, 5)),
      status: "REQUESTED",
    },
  },
  {
    id: "collab-2",
    title: "협업 · 트랙 수정",
    description: "새로운 드럼 텍스처 요청",
    startDate: formatISO(addDays(today, 1)),
    category: "COLLAB",
    collabDetails: {
      trackProducer: "Noah Kim",
      topLiner: "Sora",
      targetArtist: "LIV",
      deadline: formatISO(addDays(today, 7)),
      status: "IN_PROGRESS",
    },
  },
  {
    id: "collab-3",
    title: "협업 · 믹스 확인",
    description: "최종 믹스 승인",
    startDate: formatISO(addDays(today, 8)),
    category: "COLLAB",
    collabDetails: {
      trackProducer: "Evan Choi",
      topLiner: "Min",
      targetArtist: "ARO",
      deadline: formatISO(addDays(today, 10)),
      status: "COMPLETED",
      mixMonitorSent: false,
    },
  },
  {
    id: "hold-1",
    title: "Hold · City Lights",
    description: "픽스 전 홀드 상태",
    startDate: formatISO(addDays(today, 4)),
    category: "HOLD_FIX",
    holdFixDetails: {
      type: "HOLD",
      demoName: "City Lights",
      writers: ["Alex", "Rina"],
      splits: {
        Alex: 50,
        Rina: 50,
      },
      publishingInfo: "Peer Music",
      email: "aandr@peermusic.com",
      holdRequestedDate: formatISO(addDays(today, 1)),
      holdPeriod: "2주",
      manager: "김하늘",
    },
  },
  {
    id: "fix-1",
    title: "Fix · Golden Hour",
    description: "픽스 완료",
    startDate: formatISO(addDays(today, 5)),
    category: "HOLD_FIX",
    holdFixDetails: {
      type: "FIX",
      demoName: "Golden Hour",
      writers: ["Maya", "Jun"],
      splits: {
        Maya: 40,
        Jun: 60,
      },
      publishingInfo: "Peer Music / Universal",
      email: "sync@peermusic.com",
      productionFee: 2500,
    },
  },
  {
    id: "release-1",
    title: "Release · Aurora",
    description: "발매 확정",
    startDate: formatISO(addDays(today, 12)),
    category: "HOLD_FIX",
    holdFixDetails: {
      type: "RELEASE",
      demoName: "Aurora",
      writers: ["Jisoo", "Leo"],
      splits: {
        Jisoo: 55,
        Leo: 45,
      },
      publishingInfo: "Peer Music",
      email: "release@peermusic.com",
      productionFee: 3000,
      releaseDate: formatISO(addDays(today, 20)),
    },
  },
  {
    id: "personal-1",
    title: "개인 · 운동 루틴",
    description: "러닝 5km + 스트레칭",
    startDate: formatISO(addDays(today, 1)),
    category: "PERSONAL",
  },
  {
    id: "stock-1",
    title: "주식 · 실적 발표",
    description: "Peer Holdings Q1 발표",
    startDate: formatISO(addDays(today, 2)),
    category: "STOCK",
    stockDetails: {
      ticker: "PEER",
      relatedNewsTitle: "실적 발표 프리뷰",
      note: "발표 1시간 전 알림 설정",
      relatedNewsUrl: "",
    },
  },
];
